def attach(pid: int) -> None: ...
def seize(pid: int) -> None: ...
def detach(pid: int) -> None: ...
def cont(pid: int) -> None: ...
def interrupt(pid: int) -> None: ...
def singlestep(pid: int) -> None: ...

def getregs(pid: int) -> dict[str, int]: ...
def setregs(pid: int, regs: dict[str, int]) -> None: ...

def peek(pid: int, address: int) -> int: ...
def poke(pid: int, address: int, value: int) -> None: ...
def read_bytes(pid: int, address: int, length: int, mind_rbound: bool) -> bytearray: ...
def write_bytes(pid: int, address: int, data: bytearray, length: int, mind_rbound: bool) -> None: ...
def unwind(pid: int, step_limit: int) -> list: ...

def waitpid(pid: int) -> tuple[int, int]: ...
